public class Main {
    public static void main(String[] args) {
        OptionPane option = new OptionPane();
        option.okOption(true, "Lorem ipsum", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sit amet mauris ut risus scelerisque sodales pellentesque eget odio. Maecenas fringilla, dui at sollicitudin venenatis, libero justo commodo ligula, nec consequat justo nisi et libero. Pellentesque interdum blandit libero non dapibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed eu dapibus felis. Curabitur tellus velit, accumsan vel gravida sed, tincidunt ut est. Etiam eget dictum erat. Donec tortor dui, blandit quis porta facilisis, blandit vel mauris. Nullam venenatis urna accumsan nulla tincidunt, sit amet varius massa mollis. Nam semper lectus consectetur feugiat lobortis. Nunc gravida neque vestibulum tortor volutpat pretium vitae quis arcu. Pellentesque ullamcorper dui ligula, quis sollicitudin eros interdum quis. Proin tincidunt finibus pretium. Etiam pretium libero nulla, tempus fringilla leo sagittis eget.\n" +
                "\n" +
                "Aliquam sit amet enim congue, auctor felis ut, tristique sapien. Vivamus non massa eget neque cursus fringilla. Nam dignissim fermentum finibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras nisl arcu, rhoncus non tortor dictum, maximus placerat felis. Nulla sollicitudin commodo faucibus. Cras ullamcorper enim nec porta feugiat. Nulla at egestas est, in eleifend justo. Suspendisse quis suscipit tortor. Integer ac tristique justo. Nulla vitae ante auctor lectus cursus pellentesque a et velit. In porta tellus id ante congue, at lobortis nisl sagittis.\n" +
                "\n" +
                "Donec pharetra ultricies iaculis. Pellentesque elementum lorem tempor urna volutpat ultricies. Aliquam in dui nec neque dictum luctus at et ligula. In a feugiat felis, at ullamcorper elit. Curabitur at diam posuere, imperdiet quam nec, luctus arcu. Vivamus at nulla id purus tincidunt hendrerit. Vivamus blandit velit et rutrum auctor. Sed lacus odio, auctor eget tortor non, semper pharetra ipsum. Sed tempus porta risus in tincidunt.\n" +
                "\n" +
                "Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas dignissim leo ligula, vel sagittis lacus blandit at. Nullam arcu purus, consectetur quis congue vitae, lobortis non nunc. Praesent id tellus non turpis bibendum aliquam. Praesent a metus finibus, mollis tellus sed, sagittis quam. In mollis dictum quam tincidunt aliquam. Suspendisse eget purus feugiat, aliquam elit ut, eleifend risus.");
    }
}
